server:
  port: 8090
  servlet:
    context-path: /springBootHippo4j
management:
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  server:
    port: 29999 # 自选
  endpoints:
    web:
      base-path: ${server.servlet.context-path}/actuator
      exposure:
        include: '*' # 测试使用，开启了所有端点，生产环境不建议 *

spring:
  application:
    name: springBootHippo4j
  dynamic:
    thread-pool:
      enable: true
      # 服务端地址
      server-addr: http://localhost:6691
      # 用户名
      username: admin
      # 密码
      password: 123456
      # 租户 id, 对应 tenant 表
      namespace: hgq1
      # 项目 id, 对应 item 表
      item-id: ${spring.application.name}

